### ISSUE TITLE
Brother need autoreff for (Xenia Wallet, Aigea, Confidential Layer, functor node) it's request :)

### ISSUE THREAD

**Issue by obitoo2005** [im-hanzou/teneo-autoref#1]

**Comment by im-hanzou** [comment]
Yes maybe, I only make bots if I want to xD

**Comment by obitoo2005** [comment]
> Yes maybe, I only make bots if I want to xD

Ok bro no issue. :) ,. thanks for teneo auto reff

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Help Center](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [Help Center](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
