### ISSUE TITLE
error when activate the wallet

### ISSUE THREAD

**Issue by ene80** [im-hanzou/teneo-autoref#2]
[2024-12-31 15:41:07] [5/374] Activation error: module 'websocket' has no attribute 'create_connection'
[2024-12-31 15:41:07] [5/374] Failed to activate
[2024-12-31 15:41:07] [5/374] Failed: Account active validation failed

**Comment by Brett090** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Berge511** [comment]
Hello @ene80  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by iceyui** [comment]
Try 

> pip uninstall websocket websocket-client -y

> pip install websocket-client

Then, 
add this at main.py on line 15

`from websocket import create_connection`

**Comment by ene80** [comment]
perfect, working now
